Implement Coordinate Search
JuliaSmoothOptimizers/DerivativeFreeSolvers.jl pull request #6
Opened 2019-08-29 23:06 UTC by joaoluisro

2019-08-31 19:19 UTC, abelsiqueira requested changes
Thanks @joaoluisro, it's looking good. I just made a few corrections. You'll need to amend your commits and force push your changes.

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +			                     greedy :: Bool = true)
Fix indentation

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  @info log_header([:iter, :f, :H],[Int, T, T], hdr_override=Dict(:f=>"f(x)", :H=>"α"))
Spacing `, :H],[Int,` -> `, :H], [Int,`. And between `=>`.
You don't need `:H`, use `:α` directly, and then remove from `hdr_override`.

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  f = obj(nlp,x)
Space after `,`

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +    end
Fix indentation

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +    end
You don't need `done` nor the `while`. Line 48 always happens because it's outside the for loop, so just remove the `while`.

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +	      f_xt = obj(nlp,xt)
Space after `,`

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  k = 0
Add a condition verifying that `α > 0`, and that `β > 1`.

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +"""
Fix to
```
"""
	coordinate_search(nlp)

Text
"""
```

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  if (optimal)
No need for parenthesis

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  elseif (tired)
Also here

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  elseif (tired)
And two more places below

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +	      if (f_xt < best_f)
No parenthesis

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +    status =:unknown
Use `:acceptable` and put a space after `=`.
Also below, spaces after `=`.

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +    if (neval_obj(nlp) > max_eval && max_eval >= 0)
`neval_obj(nlp) > max_eval >= 0`

2019-08-31 19:19 UTC, abelsiqueira commented on src/coordinate_search.jl
> +                                iter = k, elapsed_time = el_time)
Aligh `iter` with `status`.

2019-08-31 21:39 UTC, abelsiqueira commented
Use `sed -i 's/\t/  /g' src/* test/*` first, then set your editor to use spaces, not tabs, then fix your indentation.

2019-08-31 21:39 UTC, abelsiqueira commented
It should be two spaces inside the `sed`.

2019-08-31 21:49 UTC, joaoluisro commented
Everything should be in order now.

2019-08-31 21:55 UTC, abelsiqueira requested changes
Thanks again. Just a few more things.

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +      coordinate_search(nlp)
4 spaces

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> + The coordinate search is a derivative free optimization method.
No spaces

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +                           α :: Real = 1.0,
Use `one(eltype(x))`

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +                           β :: Real = 2.0,
Use `2 * one(eltype(x))`.

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  α <= 0 || β <= 1 && error("Invalid Parameters.")
Use a more informative error message.

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  status =:unknown
Space after `=`

2019-08-31 21:55 UTC, abelsiqueira commented on src/coordinate_search.jl
> +      x[abs(best_i)] += sign(best_i) *  α
Remove extra space after `*`.

2019-09-04 22:21 UTC, abelsiqueira approved these changes

2019-09-04 22:21 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  k = 0
Please change to
```
α > 0 || error("Invalid Parameter: α > 0 ")
etc.
```

2019-09-04 22:21 UTC, abelsiqueira commented on src/coordinate_search.jl
> +  k = 0
In another PR

2019-09-04 22:21 UTC, merged

2019-09-04 22:21 UTC, abelsiqueira commented
Thanks!